name: CreatePages
on: 
- push
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme
    - name: Sphinx build
      run: |
        sphinx-build docs _build
        echo "root files"
        ls
        cd _build
        echo "build files:"
        ls
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: _build/
        
