name: CreatePagesAndDeploy
on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install pandas sphinx sphinx_rtd_theme
    
    - name: Sphinx build
      run: |
        sphinx-build docs _build
    - name: Artifact upload
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: _build
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1      
